# Generated by Django 4.2 on 2023-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
