# Generated by Django 4.2 on 2023-05-07 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0006_alter_cart_color_alter_cart_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('order_status', models.CharField(blank=True, choices=[('Hold', 'Hold'), ('Shipment', 'Shipment'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad')], max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Canceled', 'Canceled')], max_length=50, null=True)),
                ('ordered_product', models.ManyToManyField(to='ecom.orderedproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
