# Generated by Django 4.2 on 2023-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_order_payment_number_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cuopone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('Free_shipping', models.BooleanField()),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=50)),
                ('amount', models.FloatField()),
                ('spent_limit', models.IntegerField()),
                ('category', models.ManyToManyField(to='ecom.category')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='used_cuopone',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.cuopone'),
        ),
    ]
