# Generated by Django 4.2 on 2023-04-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_delete_test_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slider_item', models.FileField(upload_to='upload/')),
            ],
            options={
                'verbose_name': 'Video',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={'verbose_name': 'Slider Items'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Terms & Conditions'},
        ),
    ]
