# Generated by Django 4.2 on 2023-04-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_video_alter_slider_options_alter_slideritem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='button',
            field=models.ManyToManyField(blank=True, null=True, to='utilities.button'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card',
            field=models.ManyToManyField(blank=True, null=True, to='utilities.card'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='utilities.image'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slider',
            field=models.ManyToManyField(blank=True, null=True, to='utilities.slider'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='utilities.video'),
        ),
    ]
