# Generated by Django 4.2 on 2023-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_alter_aboutus_options_aboutus_button_aboutus_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button', models.ManyToManyField(blank=True, null=True, to='utilities.button')),
                ('card', models.ManyToManyField(blank=True, null=True, to='utilities.card')),
                ('image', models.ManyToManyField(blank=True, null=True, to='utilities.image')),
                ('slider', models.ManyToManyField(blank=True, null=True, to='utilities.slider')),
                ('video', models.ManyToManyField(blank=True, null=True, to='utilities.video')),
            ],
            options={
                'verbose_name': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button', models.ManyToManyField(blank=True, null=True, to='utilities.button')),
                ('card', models.ManyToManyField(blank=True, null=True, to='utilities.card')),
                ('image', models.ManyToManyField(blank=True, null=True, to='utilities.image')),
                ('slider', models.ManyToManyField(blank=True, null=True, to='utilities.slider')),
                ('video', models.ManyToManyField(blank=True, null=True, to='utilities.video')),
            ],
            options={
                'verbose_name': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button', models.ManyToManyField(blank=True, null=True, to='utilities.button')),
                ('card', models.ManyToManyField(blank=True, null=True, to='utilities.card')),
                ('image', models.ManyToManyField(blank=True, null=True, to='utilities.image')),
                ('slider', models.ManyToManyField(blank=True, null=True, to='utilities.slider')),
                ('video', models.ManyToManyField(blank=True, null=True, to='utilities.video')),
            ],
            options={
                'verbose_name': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button', models.ManyToManyField(blank=True, null=True, to='utilities.button')),
                ('card', models.ManyToManyField(blank=True, null=True, to='utilities.card')),
                ('image', models.ManyToManyField(blank=True, null=True, to='utilities.image')),
                ('slider', models.ManyToManyField(blank=True, null=True, to='utilities.slider')),
                ('video', models.ManyToManyField(blank=True, null=True, to='utilities.video')),
            ],
            options={
                'verbose_name': 'Home',
            },
        ),
    ]
