# Generated by Django 4.2 on 2023-05-01 10:51

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_testimonials_teams_services_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
