# Generated by Django 4.2 on 2023-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('button', models.ManyToManyField(blank=True, null=True, to='utilities.button')),
            ],
        ),
    ]
