# Generated by Django 4.2 on 2023-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_teamsingle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_logo', models.ImageField(upload_to='upload/')),
                ('favicon', models.ImageField(upload_to='upload/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Utilities',
            },
        ),
    ]
